const fs = require('fs');
const path = require('path');

const LIBRARY_FILE = path.join(__dirname, '../assets/data/library.json');
const AUDIO_DIR = path.join(__dirname, '../assets/audio');
const COVERS_DIR = path.join(__dirname, '../assets/covers');
const AUDIO_MAP_FILE = path.join(AUDIO_DIR, 'map.ts');
const COVERS_MAP_FILE = path.join(COVERS_DIR, 'trackMap.ts');

// Helper to normalize strings for comparison
function normalize(str) {
  if (!str) return '';
  return str.normalize("NFD").replace(/[\u0300-\u036f]/g, "") // Remove accents
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '') // Remove all non-alphanumeric
    .trim();
}

// Helper to get clean filename without extension
function getCleanName(filename) {
  return path.parse(filename).name;
}

function generateMaps() {
  console.log('Reading library...');
  const library = JSON.parse(fs.readFileSync(LIBRARY_FILE, 'utf8'));
  const tracks = library.items;
  
  console.log('Reading assets...');
  const audioFiles = fs.readdirSync(AUDIO_DIR).filter(f => f.endsWith('.mp3'));
  const coverFiles = fs.readdirSync(COVERS_DIR).filter(f => /\.(jpg|jpeg|png)$/i.test(f));

  const audioMap = {};
  const coverMap = {};
  
  let audioMatches = 0;
  let coverMatches = 0;

  tracks.forEach(track => {
    // 1. Match Audio
    if (track.audioUrl) {
      const targetName = path.basename(track.audioUrl);
      const targetNorm = normalize(getCleanName(targetName));
      
      // Try exact match first
      let match = audioFiles.find(f => f === targetName);
      
      // Try normalized match
      if (!match) {
        match = audioFiles.find(f => normalize(getCleanName(f)) === targetNorm);
      }

      // Try fuzzy match (contains)
      if (!match) {
        match = audioFiles.find(f => normalize(getCleanName(f)).includes(targetNorm) || targetNorm.includes(normalize(getCleanName(f))));
      }

      if (match) {
        audioMap[track.id] = match;
        audioMatches++;
      }
    }

    // 2. Match Cover
    if (track.imageUrl) {
      const targetName = path.basename(track.imageUrl);
      const targetNorm = normalize(getCleanName(targetName));
      
      // Try exact match first
      let match = coverFiles.find(f => f === targetName);
      
      // Try normalized match
      if (!match) {
        match = coverFiles.find(f => normalize(getCleanName(f)) === targetNorm);
      }
      
      // Try fuzzy match
      if (!match) {
        match = coverFiles.find(f => normalize(getCleanName(f)).includes(targetNorm) || targetNorm.includes(normalize(getCleanName(f))));
      }

      if (match) {
        coverMap[track.id] = match;
        coverMatches++;
      }
    }
  });

  console.log(`Matched ${audioMatches} audio files and ${coverMatches} covers for ${tracks.length} tracks.`);

  // Write Audio Map
  let audioContent = `// Generated by tools/fix_assets_maps.js\nexport const audioMap: Record<string, any> = {\n`;
  for (const [id, file] of Object.entries(audioMap)) {
    audioContent += `  '${id}': require('./${file}'),\n`;
  }
  audioContent += `};\n`;
  fs.writeFileSync(AUDIO_MAP_FILE, audioContent);
  console.log(`Wrote ${AUDIO_MAP_FILE}`);

  // Write Cover Map
  let coverContent = `// Generated by tools/fix_assets_maps.js\n`;
  coverContent += `export const coverByTrackMap: Record<string, any> = {\n`;
  for (const [id, file] of Object.entries(coverMap)) {
    coverContent += `  '${id}': require('./${file}'),\n`;
  }
  coverContent += `};\n`;
  fs.writeFileSync(COVERS_MAP_FILE, coverContent);
  console.log(`Wrote ${COVERS_MAP_FILE}`);
}

generateMaps();
