// Generated by admin-panel/tools/generateAssets.mjs
import cover_4__DOS_GRANDES_JSC_3544_JPG from './4._DOS_GRANDES_JSC_3544.JPG';
import cover_17__UN_CANTO_CELESTIAL_JSC_3582_JPG from './17._UN_CANTO_CELESTIAL_JSC_3582.JPG';
import cover_22__POR_LO_ALTO_JSC_3600_JPG from './22._POR_LO_ALTO_JSC_3600.JPG';
import cover_3__DE_FRENTE_JSC_3542_JPG from './3._DE_FRENTE_JSC_3542.JPG';
import cover_14__MI_VIDA_MUSICAL_JSC_3572_JPG from './14._MI_VIDA_MUSICAL_JSC_3572.JPG';
import cover_11__GANO_EL_FOLCLOR_JSC_3565_JPG from './11._GANO_EL_FOLCLOR_JSC_3565.JPG';
import cover_39_FESTIVAL_VALLENATO_JSC_3653_JPG from './39.FESTIVAL_VALLENATO_JSC_3653.JPG';
import cover_74__CUARTO_CONCIERTO_VALLENATO_JSC_3765_JPG from './74._CUARTO_CONCIERTO_VALLENATO_JSC_3765.JPG';
import cover_77_FIESTA_VALLENATA_VOLUMEN_5_JSC_3824_JPG from './77_FIESTA_VALLENATA_VOLUMEN_5_JSC_3824.JPG';
import cover_20_ADELANTE_JSC_3596_JPG from './20_ADELANTE_JSC_3596.JPG';
import cover_66__NACI_PARA_CANTAR_JSC_3741_JPG from './66._NACI_PARA_CANTAR_JSC_3741.JPG';

export const coverByTrackMap: Record<string, any> = {
  'trk_0djxswp': cover_4__DOS_GRANDES_JSC_3544_JPG,
  'trk_3q49o4t': cover_4__DOS_GRANDES_JSC_3544_JPG,
  'trk_zv6nwrm': cover_17__UN_CANTO_CELESTIAL_JSC_3582_JPG,
  'trk_epxzpbi': cover_22__POR_LO_ALTO_JSC_3600_JPG,
  'trk_xnqbvmp': cover_3__DE_FRENTE_JSC_3542_JPG,
  'trk_7gspukd': cover_3__DE_FRENTE_JSC_3542_JPG,
  'trk_phebo90': cover_14__MI_VIDA_MUSICAL_JSC_3572_JPG,
  'trk_093fsoh': cover_3__DE_FRENTE_JSC_3542_JPG,
  'trk_fbzkhi1': cover_4__DOS_GRANDES_JSC_3544_JPG,
  'trk_y4rw3p2': cover_4__DOS_GRANDES_JSC_3544_JPG,
  'trk_aqk4er2': cover_11__GANO_EL_FOLCLOR_JSC_3565_JPG,
  'trk_aymzuem': cover_39_FESTIVAL_VALLENATO_JSC_3653_JPG,
  'trk_5vrpb3o': cover_4__DOS_GRANDES_JSC_3544_JPG,
  'trk_eoc2vb8': cover_3__DE_FRENTE_JSC_3542_JPG,
  'trk_qt11oxl': cover_22__POR_LO_ALTO_JSC_3600_JPG,
  'trk_4dlxprq': cover_74__CUARTO_CONCIERTO_VALLENATO_JSC_3765_JPG,
  'trk_vokmo7t': cover_17__UN_CANTO_CELESTIAL_JSC_3582_JPG,
  'trk_zmxwq4h': cover_17__UN_CANTO_CELESTIAL_JSC_3582_JPG,
  'trk_loeydq0': cover_11__GANO_EL_FOLCLOR_JSC_3565_JPG,
  'trk_ntalu2v': cover_39_FESTIVAL_VALLENATO_JSC_3653_JPG,
  'trk_x97c44q': cover_17__UN_CANTO_CELESTIAL_JSC_3582_JPG,
  'trk_afovlx1': cover_39_FESTIVAL_VALLENATO_JSC_3653_JPG,
  'trk_sgltzb7': cover_17__UN_CANTO_CELESTIAL_JSC_3582_JPG,
  'trk_7rduj03': cover_77_FIESTA_VALLENATA_VOLUMEN_5_JSC_3824_JPG,
  'trk_fxez35t': cover_17__UN_CANTO_CELESTIAL_JSC_3582_JPG,
  'trk_i4y06kv': cover_17__UN_CANTO_CELESTIAL_JSC_3582_JPG,
  'trk_gn1tr7b': cover_39_FESTIVAL_VALLENATO_JSC_3653_JPG,
  'trk_3iozs2o': cover_17__UN_CANTO_CELESTIAL_JSC_3582_JPG,
  'trk_22imsu2': cover_22__POR_LO_ALTO_JSC_3600_JPG,
  'trk_3ljtrwl': cover_77_FIESTA_VALLENATA_VOLUMEN_5_JSC_3824_JPG,
  'trk_cw3njdp': cover_3__DE_FRENTE_JSC_3542_JPG,
  'trk_z2kfzfu': cover_4__DOS_GRANDES_JSC_3544_JPG,
  'trk_fgw4y5b': cover_39_FESTIVAL_VALLENATO_JSC_3653_JPG,
  'trk_838gqzm': cover_74__CUARTO_CONCIERTO_VALLENATO_JSC_3765_JPG,
  'trk_u9vwbj3': cover_17__UN_CANTO_CELESTIAL_JSC_3582_JPG,
  'trk_2d66dvr': cover_20_ADELANTE_JSC_3596_JPG,
  'trk_l9mpsff': cover_17__UN_CANTO_CELESTIAL_JSC_3582_JPG,
  'trk_pyuh3rd': cover_17__UN_CANTO_CELESTIAL_JSC_3582_JPG,
  'trk_xeznr2i': cover_17__UN_CANTO_CELESTIAL_JSC_3582_JPG,
  'trk_3j9ilp7': cover_39_FESTIVAL_VALLENATO_JSC_3653_JPG,
  'trk_sp0uchh': cover_17__UN_CANTO_CELESTIAL_JSC_3582_JPG,
  'trk_jsmh1n3': cover_3__DE_FRENTE_JSC_3542_JPG,
  'trk_dtso3kj': cover_20_ADELANTE_JSC_3596_JPG,
  'trk_mffy227': cover_74__CUARTO_CONCIERTO_VALLENATO_JSC_3765_JPG,
  'trk_yk29ggp': cover_74__CUARTO_CONCIERTO_VALLENATO_JSC_3765_JPG,
  'trk_xb5cnjy': cover_3__DE_FRENTE_JSC_3542_JPG,
  'trk_f0a62em': cover_39_FESTIVAL_VALLENATO_JSC_3653_JPG,
  'trk_r8t2li2': cover_39_FESTIVAL_VALLENATO_JSC_3653_JPG,
  'trk_gduwk9g': cover_74__CUARTO_CONCIERTO_VALLENATO_JSC_3765_JPG,
  'trk_gip7kas': cover_66__NACI_PARA_CANTAR_JSC_3741_JPG,
};
